<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Courses  Schemes</name>
   <tag></tag>
   <elementGuidId>2c711133-6137-479b-9b43-068af6480e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uppermenu']/ul/li[2]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Courses &amp; Schemes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fe46571-046c-4f42-8875-2e3a2f15a38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/school-education/academic/index.html;jsessionid=70EAD434761F4EA4156576BCAD8D3E67</value>
      <webElementGuid>62139851-308a-4395-94af-b119abab376a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Courses &amp; Schemes</value>
      <webElementGuid>4cc40960-7812-4f3d-961f-3bf2ceda6b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uppermenu&quot;)/ul[1]/li[@class=&quot;avs_node&quot;]/ul[1]/li[@class=&quot;avs_leaf&quot;]/a[1]</value>
      <webElementGuid>67ab9834-f546-4065-87ab-feffe60f9777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uppermenu']/ul/li[2]/ul/li[4]/a</value>
      <webElementGuid>a814b717-7f05-4254-ae7c-c6d6ded78db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Courses &amp; Schemes')]</value>
      <webElementGuid>493a1146-1e3b-4535-b5f5-7f2d8626bfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Five fold education'])[1]/following::a[1]</value>
      <webElementGuid>86118737-b918-4bfd-8c0b-7e7c45ee0757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[2]</value>
      <webElementGuid>688157b3-82a2-42d5-a895-b9d343719cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faculty &amp; Staff'])[1]/preceding::a[1]</value>
      <webElementGuid>bf4494ff-4240-4fd9-8c22-5376cf67f3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Activities'])[1]/preceding::a[2]</value>
      <webElementGuid>a5701253-a912-4962-90f7-9320a872ef04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Courses &amp; Schemes']/parent::*</value>
      <webElementGuid>c440f0c4-e714-4965-add3-6392f155b766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/school-education/academic/index.html;jsessionid=70EAD434761F4EA4156576BCAD8D3E67')]</value>
      <webElementGuid>89550cdc-2f68-4ca4-9ceb-0fc97af0a327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>43c9c5f1-6e17-4aad-932e-c9d390d0ffa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/school-education/academic/index.html;jsessionid=70EAD434761F4EA4156576BCAD8D3E67' and (text() = 'Courses &amp; Schemes' or . = 'Courses &amp; Schemes')]</value>
      <webElementGuid>f7612067-0205-4c26-ae68-e98884c7e188</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
