<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Education</name>
   <tag></tag>
   <elementGuidId>68dba8d1-f676-4269-9ed8-a28b7a39a5c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.avs_node > ul > li.avs_node > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Education&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>faead274-2da2-4b92-9d0c-eb7d03cd2465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/lower-menu/faculties/faculty-of-education/index.html;jsessionid=A2018961497F689BCB274CC02EA03BCB</value>
      <webElementGuid>4cabcfe4-17dd-499b-b9f1-0bd7e0bd7dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>1ad6b6c1-5cc7-4ca0-ae5f-57367bb59f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[@class=&quot;avs_node&quot;]/ul[1]/li[@class=&quot;avs_node&quot;]/a[1]</value>
      <webElementGuid>4d6ec708-075c-4610-8cbc-a61e48b7dd1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li/ul/li/a</value>
      <webElementGuid>1696edb5-82a3-4517-8036-3fa90329d283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Education')])[7]</value>
      <webElementGuid>5cbae8b2-bf1e-4e3e-8cf9-9c6a76dfcdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Architecture and Planning'])[1]/following::a[2]</value>
      <webElementGuid>6d6dd069-62f8-425e-9d7e-c85a372b060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fine Arts'])[1]/preceding::a[1]</value>
      <webElementGuid>1c8e1e90-8d02-4de0-85ba-951291ba1130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Science'])[2]/preceding::a[2]</value>
      <webElementGuid>d3b270a8-f43d-472e-936b-0712b9ee516a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/lower-menu/faculties/faculty-of-education/index.html;jsessionid=A2018961497F689BCB274CC02EA03BCB')]</value>
      <webElementGuid>2aa71fa9-6ae1-40f0-aa4a-865a6948ed7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li/ul/li/a</value>
      <webElementGuid>730cfb28-fc90-49f6-950e-38a2dc3c2ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/lower-menu/faculties/faculty-of-education/index.html;jsessionid=A2018961497F689BCB274CC02EA03BCB' and (text() = 'Education' or . = 'Education')]</value>
      <webElementGuid>cc43d69b-db62-4e1d-b9b5-02f66bcadbc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
