<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Faculties</name>
   <tag></tag>
   <elementGuidId>8a35cb87-77fd-49c6-be40-36fda2270273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu > ul > li.avs_node > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Faculties&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b672ce58-3ce7-4097-8c9b-fe45a0daf579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/lower-menu/faculties/index.html</value>
      <webElementGuid>0f243183-800c-4cdd-962f-6e6787f4cdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Faculties      </value>
      <webElementGuid>2da1e2a5-225c-4642-9b73-5400e2250a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[@class=&quot;avs_node&quot;]/a[1]</value>
      <webElementGuid>24136076-857c-4236-9645-04ebcd381ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li/a</value>
      <webElementGuid>3984a234-9e54-46cb-bce1-252bc1be999e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Faculties')]</value>
      <webElementGuid>28f016df-c94c-499b-8e63-02121f6aa58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Architecture and Planning'])[1]/following::a[1]</value>
      <webElementGuid>81ceeb77-466f-4aa1-92f8-d19dceafb865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visual Arts'])[1]/following::a[2]</value>
      <webElementGuid>b039b240-63de-4eef-81c1-da7fbd568a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[2]/preceding::a[1]</value>
      <webElementGuid>d0fb16aa-44c8-4f4a-bb02-de58ded91480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fine Arts'])[1]/preceding::a[2]</value>
      <webElementGuid>7bd768a4-688c-4292-8b33-f3938cd0d4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Faculties']/parent::*</value>
      <webElementGuid>040d2243-4865-46f6-91a0-8c2ac254000d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/lower-menu/faculties/index.html')]</value>
      <webElementGuid>7d45a472-0507-4a42-82f5-cd2db77f32fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li/a</value>
      <webElementGuid>abb8aa25-ee29-40e8-9bdd-e76ab6e03af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/lower-menu/faculties/index.html' and (text() = 'Faculties      ' or . = 'Faculties      ')]</value>
      <webElementGuid>c513772e-2bb2-452b-9e15-854bf0c54d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
