<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>21ac0e0d-cfff-45f0-af3f-84e55675abad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newwrapper']/table/tbody/tr/td/div/div[2]/div[6]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(6) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>169c4089-c4d1-4b62-9f10-053cab2c6e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/banasthali/images/1000.gif?ver=2023.1</value>
      <webElementGuid>740ea4f5-0620-4213-bab5-9425c5bf5449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>06e28a1c-ec13-4263-b4ea-200710f5a25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newwrapper&quot;)/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[2]/div[6]/a[1]/img[1]</value>
      <webElementGuid>a1bbd52d-ec3a-4e31-9d5e-33f46b2310e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newwrapper']/table/tbody/tr/td/div/div[2]/div[6]/a/img</value>
      <webElementGuid>1e84ac70-c3d7-401d-a3c7-5ed1856a9bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>c896372e-ed88-4024-ace7-dc26422d603d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/banasthali/images/1000.gif?ver=2023.1']</value>
      <webElementGuid>ca4a71aa-c483-4f88-be64-a5fa3008290f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
