<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Education</name>
   <tag></tag>
   <elementGuidId>f458dcd5-43a8-4e89-8e2a-b036594cfd20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.avs_node > ul > li.avs_node</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/ul/li/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu li >> internal:has-text=/^Education$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6a053df6-d45b-4bea-9e4f-bdf4a8ee4251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avs_node</value>
      <webElementGuid>d2bd0012-18dd-4b84-91c7-dd954914485c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>be78f54d-3e80-4417-806d-2abd9a77c8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[1]/li[@class=&quot;avs_node&quot;]/ul[1]/li[@class=&quot;avs_node&quot;]</value>
      <webElementGuid>0070f583-3fca-4313-bd07-307d27366e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/ul/li/ul/li</value>
      <webElementGuid>f5b912e4-788a-4201-b8a5-150ee87fc2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Architecture and Planning'])[1]/following::li[2]</value>
      <webElementGuid>ae4b9f91-66f9-43ed-ac09-32837756ae04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fine Arts'])[1]/preceding::li[1]</value>
      <webElementGuid>d6e99a5e-33ad-4675-9479-62b2be847bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li/ul/li</value>
      <webElementGuid>d4515ed3-dfb6-400c-8280-7903a7b5577c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Education' or . = 'Education')]</value>
      <webElementGuid>edde1a3c-7d45-4248-9cb4-6f4477115675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
