<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Physical</name>
   <tag></tag>
   <elementGuidId>20f272f1-c66f-4212-8d05-2be79962bdf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='innerTextContent']/div/p[2]/span[2]/span/a/strong/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Physical:&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ca9da5f-f2f7-4efa-ae4f-e6c7b9dba75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Physical:</value>
      <webElementGuid>f75428d4-a005-4ef5-922c-20c8e1b61cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;innerTextContent&quot;)/div[1]/p[2]/span[2]/span[1]/a[1]/strong[1]/span[1]</value>
      <webElementGuid>63381efd-29b1-47e8-9843-54397d9e8dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerTextContent']/div/p[2]/span[2]/span/a/strong/span</value>
      <webElementGuid>d487d34c-0a08-401e-aa5d-bb65b72a11fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aesthetic'])[1]/preceding::span[7]</value>
      <webElementGuid>e5db87c7-7ae1-43e4-beee-a53d38fc725a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Physical:']/parent::*</value>
      <webElementGuid>5afcb391-bda2-485e-a7ed-787402b3f1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/span</value>
      <webElementGuid>f5c662cc-0798-4cc0-ac81-043035322ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Physical:' or . = 'Physical:')]</value>
      <webElementGuid>1d23340c-115d-48a6-a4ac-046dedee4e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
