<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admissions</name>
   <tag></tag>
   <elementGuidId>a0e5439b-8480-4652-ab80-7ccb05a263ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.avs_leaf > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bioScienceLeftLower']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admissions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d3bd3ff-19eb-4870-8d0a-079b197cc266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemistry/admissions/index.html</value>
      <webElementGuid>0c5a4d0b-cf0a-418c-866a-b8edc2c578be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admissions</value>
      <webElementGuid>add01196-e1de-4ecb-84b5-a34645eb1b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bioScienceLeftLower&quot;)/ul[1]/li[@class=&quot;avs_leaf&quot;]/a[1]</value>
      <webElementGuid>13b4c567-f503-4aaa-85d2-debe98af1a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bioScienceLeftLower']/ul/li/a</value>
      <webElementGuid>15d88ea1-cfc5-486a-b15d-f03eebe6708d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admissions')]</value>
      <webElementGuid>bb850219-dbd4-4b49-82a4-e29e2b59affe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chemical Engineering'])[1]/following::a[1]</value>
      <webElementGuid>69d404c5-28b1-4ee3-8164-75d3e93b5dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pharmacy'])[1]/following::a[2]</value>
      <webElementGuid>c7710c3a-fdbb-4619-9373-3bb4d94c7770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses And Schemes'])[1]/preceding::a[1]</value>
      <webElementGuid>3544a7d6-b203-4a70-b99f-b6a6f4710527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faculty'])[1]/preceding::a[2]</value>
      <webElementGuid>a899cc5f-a8b2-4a04-9405-7a4e6368c574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admissions']/parent::*</value>
      <webElementGuid>a6248846-4694-4c33-a947-60c1004863c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemistry/admissions/index.html')]</value>
      <webElementGuid>c0c170a1-1dfb-4d84-a1c5-e346b6bf1dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>ca5e6d75-76f7-4df2-b1a6-ad4929c14d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemistry/admissions/index.html' and (text() = 'Admissions' or . = 'Admissions')]</value>
      <webElementGuid>783166ff-6abb-492d-9ba6-d1f15706cb02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
