<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chemical Engineering</name>
   <tag></tag>
   <elementGuidId>573b6309-f9de-4197-9c7a-78e906dc81a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bioScienceLeftTop']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Chemical Engineering&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ec4b347-b62b-4f1f-baa3-880516495a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemical/index.html</value>
      <webElementGuid>ae7f07f2-5a3d-474b-8cc8-ef8015923d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chemical Engineering</value>
      <webElementGuid>1f054f79-42ae-458c-bc24-3db26765d4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bioScienceLeftTop&quot;)/ul[1]/li[@class=&quot;avs_node&quot;]/a[1]</value>
      <webElementGuid>c7a81d11-4553-44b0-831e-6d79e5a6b529</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bioScienceLeftTop']/ul/li[4]/a</value>
      <webElementGuid>653a801d-9785-476e-b076-b929ff03c40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Chemical Engineering')]</value>
      <webElementGuid>0da2b7f1-3b9c-4d66-92a9-08fd624f9489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pharmacy'])[1]/following::a[1]</value>
      <webElementGuid>7e8b0b16-24d4-4ff2-bb1b-4bc69d755053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chemistry'])[2]/following::a[2]</value>
      <webElementGuid>122f7e9c-43ba-4d83-9e18-c0117f9a8b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissions'])[2]/preceding::a[1]</value>
      <webElementGuid>583381c5-79bf-4fae-bcc7-8b86c795dedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses And Schemes'])[1]/preceding::a[1]</value>
      <webElementGuid>7c15ead9-34cb-4527-9d3f-ce6b91a09e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chemical Engineering']/parent::*</value>
      <webElementGuid>2eb909b0-bf69-4eae-9c22-bca81d6788ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemical/index.html')]</value>
      <webElementGuid>536150b3-03b0-4284-a861-93d0900bdcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>9b4fe9d4-fb75-4983-9392-09c7ed7146d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemical/index.html' and (text() = 'Chemical Engineering' or . = 'Chemical Engineering')]</value>
      <webElementGuid>ab056b2b-4297-45d8-99b3-82c41a47a296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
