<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpwww.banasthali.org</name>
   <tag></tag>
   <elementGuidId>21792292-bb6f-43da-a764-da80c8a741f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/table/tbody/tr[3]/td[5]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5) > div > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;http://www.banasthali.org&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c49a7236-08cb-459f-82b9-828dfac13b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.banasthali.org</value>
      <webElementGuid>8d6117a8-afc1-475c-924c-396e8a4a5acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>http://www.banasthali.org</value>
      <webElementGuid>0e8fabc2-0477-4732-b0fb-ed85fea5b22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[2]/table[1]/tbody[1]/tr[3]/td[5]/div[1]/a[1]</value>
      <webElementGuid>c17653eb-6ae7-4975-9bf0-bec02c44a173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/table/tbody/tr[3]/td[5]/div/a</value>
      <webElementGuid>a3b2c796-7d7d-4295-97b3-9d46f414e2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'http://www.banasthali.org')]</value>
      <webElementGuid>279a4782-350a-4033-b5f4-414d6765be60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Submission'])[1]/following::a[1]</value>
      <webElementGuid>6580f478-1bde-4506-9799-7c4bd55e2fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='http://www.banasthali.org']/parent::*</value>
      <webElementGuid>3616d0ad-692a-4e81-b56f-5a0479aa1a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.banasthali.org']</value>
      <webElementGuid>f7e3c618-729f-4c03-ba33-13dc9c3bb50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/a</value>
      <webElementGuid>f40048ad-75a4-4a59-9138-3e81ac83fc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.banasthali.org' and (text() = 'http://www.banasthali.org' or . = 'http://www.banasthali.org')]</value>
      <webElementGuid>d69f5d22-6914-43b8-80d7-b333a3fb8d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
