<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>921277c9-ae89-44e6-a939-88480e6fa923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='innerTextContent']/div/table/tbody/tr[2]/td[2]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > div > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Degree&quot;s] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>edd489fd-2602-4961-b48c-e2b4345d074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/examination/downloadimg.jpg</value>
      <webElementGuid>8741c4fc-04ad-4a47-a753-e060085958a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>01c1213b-526c-44b4-8cd9-0bb32c53b807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>5ba7c8df-c87e-406d-8b9a-540882c06049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>bb94585e-0e5b-470c-9c7e-f6ba5417dd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;innerTextContent&quot;)/div[1]/table[1]/tbody[1]/tr[2]/td[2]/a[1]/div[1]/img[1]</value>
      <webElementGuid>66da3180-08ec-4eb8-a73a-b54e03f12c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerTextContent']/div/table/tbody/tr[2]/td[2]/a/div/img</value>
      <webElementGuid>2079775c-46d1-45b4-a79b-412b0561f908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=' ']</value>
      <webElementGuid>11a78543-c522-42f3-8a31-8b6ba75a800b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>4cf998f6-0cc3-4e34-abe7-6fa853236188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/banasthali/wcms/en/home/examination/downloadimg.jpg']</value>
      <webElementGuid>ac05d8f5-fbdd-4daa-959e-fbc9457712af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
