<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_B.A</name>
   <tag></tag>
   <elementGuidId>7d722a02-1563-4986-82ce-68a7c2e18ef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='AutoNumber2']/tbody/tr/td[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;B.A.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a3fec856-178a-45a3-8a59-f94be9f35583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>B.A.</value>
      <webElementGuid>98013d16-d5c2-43e7-a0a2-ee5471cd0002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AutoNumber2&quot;)/tbody[1]/tr[1]/td[2]/div[1]/span[1]</value>
      <webElementGuid>db194147-7b2a-4680-baad-a254068e2fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AutoNumber2']/tbody/tr/td[2]/div/span</value>
      <webElementGuid>e3b0be1c-961d-481c-a04e-5c6e4c7c9316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course  Offered'])[1]/following::span[1]</value>
      <webElementGuid>ce307190-d4a9-4527-9d22-bba62c0d94a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ph.D.(physical Education)'])[1]/preceding::span[1]</value>
      <webElementGuid>42fd70e0-3080-4dbd-8eab-b43d1fc3ced6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='B.A.']/parent::*</value>
      <webElementGuid>f80d0446-2446-46dd-84ca-031d91bb6017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>50eeb2bf-bc9e-4b2b-97e2-998fe1b443e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'B.A.' or . = 'B.A.')]</value>
      <webElementGuid>3f44a7ad-4dca-4575-97b8-518c4763c9fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
