<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DOWNLOADS</name>
   <tag></tag>
   <elementGuidId>1fa78efa-3244-4d01-9399-7dd764362985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newheader']/table/tbody/tr/td/table/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.linkRhts_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;DOWNLOADS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03cee1b6-4905-4d50-baf3-48554b44cdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/downloads/index.html;jsessionid=280956BA0E94CCBA2606B62A14910DF3</value>
      <webElementGuid>25f124fe-9f43-4200-a87e-f450ea2055ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkRhts_en</value>
      <webElementGuid>fe734581-c769-4c12-a32a-5ee746f94caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOWNLOADS</value>
      <webElementGuid>40d22d01-4001-4407-9424-baa0f0908f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newheader&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;top-right-link&quot;]/a[@class=&quot;linkRhts_en&quot;]</value>
      <webElementGuid>ed9fcc2c-b5c0-47cc-80a7-b7320b334712</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newheader']/table/tbody/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>15ca484e-4931-4ac0-87cf-d146d5b798d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DOWNLOADS')]</value>
      <webElementGuid>acb18edc-d5d9-4da8-b225-dd7116d16548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PHOTOGALLERY'])[1]/preceding::a[1]</value>
      <webElementGuid>ed7d2fbe-cde9-4ba8-a86f-d18cde4ebee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DOWNLOADS']/parent::*</value>
      <webElementGuid>eba5bf01-7c0e-4127-b665-833f07e6464f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/downloads/index.html;jsessionid=280956BA0E94CCBA2606B62A14910DF3')]</value>
      <webElementGuid>be9a8372-143c-4868-ba75-f7b8aaaa4ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>e518eeed-1749-490e-ad4d-e0b9a131eb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/downloads/index.html;jsessionid=280956BA0E94CCBA2606B62A14910DF3' and (text() = 'DOWNLOADS' or . = 'DOWNLOADS')]</value>
      <webElementGuid>b263a8cc-f2af-4c38-88ef-7a8f97713dfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
