<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e8244f08-4e86-4a2e-9f09-f5e94997bfb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newwrapper']/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr[3]/td/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;\&quot;Banasthali is enshrined in my heart\&quot; - Mahatma Gandhi (1946) \&quot;If I had been a girl I would have come to Banasthali for my education\&quot; -Pandit Nehru (1945) Accredited with the highest possible grade 'A++' with CGPA 3.63/4.00 by NAAC Banasthali Vidyapith aims at the synthesis of spiritual values and scientific achievements of both the East and the West. Its educational programme is based on the concept of \&quot;Panchmukhi Shiksha\&quot; and aims at all round harmonious development of personality. Emphasis on Indian culture and thought characterized by simple living and khadi wearing are hallmarks of life at Banasthali.&quot;s] >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ee2003fa-5adf-40f5-ac2a-d32fc76c6adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/banasthali/images/banasthali_panchmuki.gif</value>
      <webElementGuid>aa3a5b23-ee20-44ed-9774-bc4f0fbca557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>263</value>
      <webElementGuid>10d1926c-f5e0-45e3-a490-e00298c2ae50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8a2532e-a7f5-416c-a759-4b11191a33b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newwrapper&quot;)/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[3]/td[1]/a[1]/img[1]</value>
      <webElementGuid>f4b16f24-ab0f-485a-bf76-e187a3ebb998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newwrapper']/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr[3]/td/a/img</value>
      <webElementGuid>7650ab8d-ba67-4817-b899-c7df334cf698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>1b9749d5-01ba-4b43-8521-577d12768868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/banasthali/images/banasthali_panchmuki.gif']</value>
      <webElementGuid>24ab813f-e1c9-4030-be5f-1f05cb8ceed3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
