<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d08efae6-39af-44b6-b1ae-49145cc689d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newwrapper']/table/tbody/tr/td/div/div[2]/div[6]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(6) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f309b3ab-497c-43fb-af8f-392f644dee72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/banasthali/images/1000.gif?ver=2023.1</value>
      <webElementGuid>cfab30c1-202f-49ed-80f0-60657aaa47b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dafcdc03-48d1-4d97-af53-ac4c9052b15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newwrapper&quot;)/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[2]/div[6]/a[1]/img[1]</value>
      <webElementGuid>fbf18005-40d4-48b2-8a60-7144c65f6c43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newwrapper']/table/tbody/tr/td/div/div[2]/div[6]/a/img</value>
      <webElementGuid>4942ba59-c6d1-4034-bcb3-3d3eaf23f252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>f9ed7be1-383e-4e58-9a3b-c65863642a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/banasthali/images/1000.gif?ver=2023.1']</value>
      <webElementGuid>530d58a3-2c1c-4a9f-9fdc-bf37db0f56cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
