<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u_Scholarships awarded by the Vidyapith</name>
   <tag></tag>
   <elementGuidId>cfedff6d-a049-40c7-8fcc-e79088c11d7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='innerTextContent']/div/div/span/strong/u</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Scholarships awarded by the Vidyapith&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>18aa3419-f74f-4bf4-bf9a-04f049498236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scholarships awarded by the Vidyapith</value>
      <webElementGuid>04f0f3eb-b35f-4adc-a62e-325d44b0803c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;innerTextContent&quot;)/div[1]/div[1]/span[1]/strong[1]/u[1]</value>
      <webElementGuid>04b8abf6-5fa3-4e21-b707-d06c2c45ef1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerTextContent']/div/div/span/strong/u</value>
      <webElementGuid>e48f0364-d9d4-4f4f-ad03-78d856b0e0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scholarships'])[3]/following::u[1]</value>
      <webElementGuid>8a9dbf7e-0a09-4d0b-9f01-ad9026833e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A. Merit Scholarships'])[1]/preceding::u[1]</value>
      <webElementGuid>cb6878c4-8b76-49ac-aece-591e7733b6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Scholarships awarded by the Vidyapith']/parent::*</value>
      <webElementGuid>fbd5d4c3-f3bd-47b6-87f0-a5fd5a0eaeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>1bda889c-3542-4b23-96d5-8db291dbb878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'Scholarships awarded by the Vidyapith' or . = 'Scholarships awarded by the Vidyapith')]</value>
      <webElementGuid>7d828fbf-1d4c-4968-93f9-0610d1228da0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
