<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1fd4e1ff-d712-449e-8f02-e7002790fafc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shado_right']/table/tbody/tr[2]/td/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.left_studnt_img > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3dd4be11-8e40-4bd2-8929-bfe3d111b337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/banasthali/images/schol_edu_Lft_stdcrner.gif</value>
      <webElementGuid>974e6a39-f790-4d84-93dd-2c2b163666dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90ca7f78-97c9-4cca-95ed-27637462532f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shado_right&quot;)/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[@class=&quot;left_studnt_img&quot;]/a[1]/img[1]</value>
      <webElementGuid>c03dc7ce-db5d-4056-892b-5693f2303ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shado_right']/table/tbody/tr[2]/td/div/div[2]/a/img</value>
      <webElementGuid>22d00dca-8619-4598-ac09-cf1ffd5cb312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>495fe532-d5f1-4343-9c19-76ef65617a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/banasthali/images/schol_edu_Lft_stdcrner.gif']</value>
      <webElementGuid>51b6a415-f0e5-467d-8cef-dece936bc867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
