<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Placements</name>
   <tag></tag>
   <elementGuidId>45e08032-cba1-4d81-8a5a-b7e1c6d39703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bioScienceLeftLower']/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Placements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0443411-ce47-4cda-84f9-7bb39ed6a380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemical/placements/index.html</value>
      <webElementGuid>fdad80be-5fa4-4421-bceb-b4da4c8e8c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Placements</value>
      <webElementGuid>9b0c6f1a-b1cf-4d2d-90b2-f50e0e655655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bioScienceLeftLower&quot;)/ul[1]/li[@class=&quot;avs_leaf&quot;]/a[1]</value>
      <webElementGuid>8d406ba9-4b98-41a7-9031-3c5cc0555bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bioScienceLeftLower']/ul/li[6]/a</value>
      <webElementGuid>7498dc3f-471f-4034-94c3-37c17826e2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Placements')]</value>
      <webElementGuid>fd6fae77-9d78-4d29-94b7-b984aeac7a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research'])[1]/following::a[1]</value>
      <webElementGuid>898c1ad9-90cb-45ec-ae4b-550f9864dc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infrastructure'])[1]/following::a[2]</value>
      <webElementGuid>78bab65b-5e18-4757-9e6e-73ac1b0af5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[1]</value>
      <webElementGuid>b0605dd7-f4e7-42f1-960d-839397c933ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department of Chemical Engineering'])[1]/preceding::a[2]</value>
      <webElementGuid>f82b96b1-6a3a-4ab9-84a7-e45256973bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Placements']/parent::*</value>
      <webElementGuid>baeb9e7b-a3f8-403b-90da-13ca3268079d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemical/placements/index.html')]</value>
      <webElementGuid>3263b7ed-eeb7-4bce-b74b-0cb413e612b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>fcd53d29-e83d-4217-a33f-9501ee5d5dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/lower-menu/faculties/life-sciences/dep-of-chemical/placements/index.html' and (text() = 'Placements' or . = 'Placements')]</value>
      <webElementGuid>be18be60-8cd5-4b8c-8358-63d7d75b9fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
