<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>300c3b58-3aad-488e-b39d-b88220d28f20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shado_right']/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr[2]/td/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td > img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5dd0ee5b-a226-48a6-a560-cb04f8bca9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/banasthali/images/school_edu_header.gif</value>
      <webElementGuid>501e93b8-e068-4ae5-880e-dd66f85cffe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1019</value>
      <webElementGuid>24d642d0-ce43-4c12-b5c6-d83c8ad1e758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>194</value>
      <webElementGuid>8014bd16-0bb8-40ed-9076-626d650fcefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>usemap</name>
      <type>Main</type>
      <value>#Map</value>
      <webElementGuid>bd4c78b5-a542-4bc5-af46-d9fb947adc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e8b3f9a-844d-4f81-8345-cd7d292831dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shado_right&quot;)/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;educationheader&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/img[1]</value>
      <webElementGuid>6b1a83d5-a562-4473-b89c-43a1db9b6c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shado_right']/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr[2]/td/img</value>
      <webElementGuid>8f94ec8c-f8c3-4785-a49b-f47bf29c60c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/img</value>
      <webElementGuid>9b23b676-fac2-46f2-b0cc-cff458922c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/banasthali/images/school_edu_header.gif']</value>
      <webElementGuid>5715cda2-50ae-4eb3-9652-e741135cfd19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
