<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>089d399f-ab73-4bc4-94f3-4f67e49a5160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shado_right']/table/tbody/tr[2]/td/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.left_studnt_img > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c2d7a72f-15b5-4897-9d46-a40bde4251ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/banasthali/images/schol_edu_Lft_stdcrner.gif</value>
      <webElementGuid>268b9d74-13ae-4f34-88e9-027328eceb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2028fab1-8e10-4569-b161-c6bffc38226e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shado_right&quot;)/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[@class=&quot;left_studnt_img&quot;]/a[1]/img[1]</value>
      <webElementGuid>11d88526-57ef-45ae-be8d-c243d302c153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shado_right']/table/tbody/tr[2]/td/div/div[2]/a/img</value>
      <webElementGuid>9663541a-3b6f-4683-b54a-c21096566b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>c6c9f4c6-a33b-42cc-adca-55b568211d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/banasthali/images/schol_edu_Lft_stdcrner.gif']</value>
      <webElementGuid>3a1dfb28-e34b-4355-aa0c-b2cfc891a054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
