<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Examination</name>
   <tag></tag>
   <elementGuidId>ff3ae9bd-bd6e-45ca-851e-99d69f098293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uppermenu']/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uppermenu > ul > li.avs_leaf > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Examination&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d2d9910-d95f-48c8-afb5-e60dcd595007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banasthali/wcms/en/home/examination/index.html</value>
      <webElementGuid>1d3206b3-8a86-4e17-a1f7-c9ebbc47f7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Examination</value>
      <webElementGuid>ec468ac1-efd0-49fe-8584-04795e58a1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uppermenu&quot;)/ul[1]/li[@class=&quot;avs_leaf&quot;]/a[1]</value>
      <webElementGuid>f9b0b873-d729-44f0-99cf-45ca10238833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uppermenu']/ul/li[7]/a</value>
      <webElementGuid>ac40b7ce-90f8-4372-baec-3e48aef9032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Examination')]</value>
      <webElementGuid>69646bbe-f756-428e-a955-f1f4a5bd578b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Resources'])[1]/following::a[1]</value>
      <webElementGuid>0956b180-2a7b-41f4-b9ca-7908c4867343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[1]/following::a[2]</value>
      <webElementGuid>9dc66ade-db91-44ae-9c19-844572759cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[1]/preceding::a[1]</value>
      <webElementGuid>5a8e647b-0e54-4e8a-8a4f-d54a115edc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANASTHALI RADIO'])[1]/preceding::a[2]</value>
      <webElementGuid>79403bfa-d164-45f0-909a-8aa378309332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Examination']/parent::*</value>
      <webElementGuid>7218bda4-49ba-4c9d-ba39-eeb8aa921739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banasthali/wcms/en/home/examination/index.html')]</value>
      <webElementGuid>eb9b7627-ee63-44c8-9c8e-31c130e56009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>99aa0d41-5850-4ac9-afa6-833f4538feae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banasthali/wcms/en/home/examination/index.html' and (text() = 'Examination' or . = 'Examination')]</value>
      <webElementGuid>f286201d-e24a-471f-9810-f1181d09bc2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
