<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Examination</name>
   <tag></tag>
   <elementGuidId>2eb172ce-edea-4f38-bdb2-7e31b004e91b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uppermenu']/ul/li[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uppermenu > ul > li.avs_leaf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Examination&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b1b298b0-663a-4983-a97b-98ef2b9640a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avs_leaf</value>
      <webElementGuid>2add1fcf-0262-4db2-932e-bee7dcc48606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Examination</value>
      <webElementGuid>c55c3ca3-7a17-4358-aa06-71e908119b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uppermenu&quot;)/ul[1]/li[@class=&quot;avs_leaf&quot;]</value>
      <webElementGuid>3fa9b71e-adf9-4757-acb3-bea8ddf62674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uppermenu']/ul/li[7]</value>
      <webElementGuid>12390ce1-5afd-40d5-8c2b-798016d2c0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Resources'])[1]/following::li[1]</value>
      <webElementGuid>68b14526-ad1c-4b98-8236-80de6402be83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[1]/following::li[2]</value>
      <webElementGuid>cee78d0a-16f0-4742-944c-fc6de7c8ebf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[1]/preceding::li[1]</value>
      <webElementGuid>7f845b8a-4599-4f36-8048-8eddb53cbc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>e6c44ace-460a-4d46-8f3e-545bd33aea8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Examination' or . = 'Examination')]</value>
      <webElementGuid>8510ad9d-7e97-45a6-a52f-8b36f4597d0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
