<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpwww.banasthali.org</name>
   <tag></tag>
   <elementGuidId>3863704e-bb32-4241-9379-80355920321b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5) > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/table/tbody/tr[3]/td[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;http://www.banasthali.org&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d40b349a-b1c6-4f7d-b1c4-f66c55190b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.banasthali.org</value>
      <webElementGuid>49b36ecb-4c99-424e-8b16-934ea6f088b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>http://www.banasthali.org</value>
      <webElementGuid>1baa93e1-9f97-481c-bb12-97fc41a0b561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[2]/table[1]/tbody[1]/tr[3]/td[5]/div[1]/a[1]</value>
      <webElementGuid>a096604e-4ab5-40f5-931f-8db9ae557cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/table/tbody/tr[3]/td[5]/div/a</value>
      <webElementGuid>23ea03c0-bddc-480f-b785-4b8631899d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'http://www.banasthali.org')]</value>
      <webElementGuid>e437f2f3-c11a-4c82-8bc2-d287ef82501e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Submission'])[1]/following::a[1]</value>
      <webElementGuid>e5a862a1-79a4-4577-9a3b-9c17a29e97ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='http://www.banasthali.org']/parent::*</value>
      <webElementGuid>cbe3835c-8ec4-4c8e-841e-7e3ebfcc3ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.banasthali.org']</value>
      <webElementGuid>84799de7-811c-41de-8dbd-5d460a66eff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/a</value>
      <webElementGuid>d3ad71fc-8eb0-4e32-b7b6-36cd40b5d715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.banasthali.org' and (text() = 'http://www.banasthali.org' or . = 'http://www.banasthali.org')]</value>
      <webElementGuid>2b133365-ab50-40bf-a2cc-7a36eacecfce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
